version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis-queue
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
