version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis-queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "supersecretpassword"]

  task_queue:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=supersecretpassword
    depends_on:
      - redis
    ports:
      - "8001:8001"
    volumes:
      - shared_images:/data/images  # <-- mount shared volume untuk image

volumes:
  redis_data:
  shared_images:
